#!/usr/bin/env python3
"""Generate firmware/assets/avatars/avatars.h — 12 fun 48×48 RGB565 creature placeholders."""

from __future__ import annotations

import math
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "assets" / "avatars" / "avatars.h"

SIZE = 48
N = 12

# Body, face, eye, accent per slot (creature palette)
PALETTES = [
    ((0x5A, 0xA0, 0xE8), (0x2A, 0x50, 0x78), (0x10, 0x14, 0x18), (0xE8, 0xC0, 0x40)),
    ((0xE8, 0x7A, 0x9A), (0x88, 0x3A, 0x5A), (0x10, 0x14, 0x18), (0xFF, 0xFF, 0xFF)),
    ((0x7A, 0xC4, 0x7A), (0x3A, 0x74, 0x3A), (0x10, 0x14, 0x18), (0xE8, 0xC0, 0x40)),
    ((0xC0, 0x70, 0xE8), (0x60, 0x30, 0x88), (0x10, 0x14, 0x18), (0x7A, 0xD4, 0xE8)),
    ((0xE8, 0xA8, 0x7A), (0x88, 0x58, 0x3A), (0x10, 0x14, 0x18), (0xFF, 0x6B, 0x6B)),
    ((0x4E, 0xCD, 0xC4), (0x2E, 0x8D, 0x84), (0x10, 0x14, 0x18), (0xE8, 0xF0, 0xE8)),
    ((0xFF, 0x6B, 0x6B), (0xAA, 0x3A, 0x3A), (0x10, 0x14, 0x18), (0xE8, 0xC0, 0x40)),
    ((0x7A, 0xD4, 0xE8), (0x3A, 0x84, 0x98), (0x10, 0x14, 0x18), (0xE8, 0xC0, 0x40)),
    ((0xD4, 0xA0, 0xE8), (0x84, 0x50, 0x98), (0x10, 0x14, 0x18), (0x5A, 0xA0, 0xE8)),
    ((0xE8, 0xC0, 0x40), (0x98, 0x80, 0x20), (0x10, 0x14, 0x18), (0x5A, 0xA0, 0xE8)),
    ((0x90, 0xB8, 0x50), (0x50, 0x78, 0x30), (0x10, 0x14, 0x18), (0xE8, 0xA8, 0x7A)),
    ((0xB0, 0x90, 0xE8), (0x60, 0x50, 0x98), (0x10, 0x14, 0x18), (0x4E, 0xCD, 0xC4)),
]


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def circle_hit(x: float, y: float, cx: float, cy: float, r: float) -> bool:
    return math.hypot(x - cx, y - cy) < r


def render_slot(slot: int) -> list[int]:
    body, face, eye, accent = PALETTES[slot % len(PALETTES)]
    bg = (0x10, 0x14, 0x18)
    pixels = [rgb565(*bg)] * (SIZE * SIZE)
    cx, cy = SIZE / 2, SIZE / 2 + 2
    ear_y = cy - 14
    for y in range(SIZE):
        for x in range(SIZE):
            # ears / horns vary by slot
            if slot % 3 == 0:
                if circle_hit(x, y, cx - 12, ear_y, 5) or circle_hit(x, y, cx + 12, ear_y, 5):
                    pixels[y * SIZE + x] = rgb565(*accent)
            elif slot % 3 == 1:
                if circle_hit(x, y, cx - 10, ear_y + 4, 4):
                    pixels[y * SIZE + x] = rgb565(*accent)
                if circle_hit(x, y, cx + 10, ear_y + 4, 4):
                    pixels[y * SIZE + x] = rgb565(*accent)
            if circle_hit(x, y, cx, cy, 17):
                pixels[y * SIZE + x] = rgb565(*body)
            if circle_hit(x, y, cx, cy + 2, 12):
                pixels[y * SIZE + x] = rgb565(*face)
            if circle_hit(x, y, cx - 5, cy - 1, 2.5) or circle_hit(x, y, cx + 5, cy - 1, 2.5):
                pixels[y * SIZE + x] = rgb565(*eye)
            # mouth
            if abs(y - (cy + 6)) < 1.2 and abs(x - cx) < 5:
                pixels[y * SIZE + x] = rgb565(*accent)
    return pixels


def c_array(name: str, values: list[int]) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    row: list[str] = []
    for i, v in enumerate(values):
        row.append(f"0x{v & 0xFF:02x}")
        row.append(f"0x{(v >> 8) & 0xFF:02x}")
        if len(row) >= 24 or i == len(values) - 1:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "#pragma once",
        "/* Generated by scripts/gen_avatars.py — do not edit by hand. */",
        "#include <stdint.h>",
        "#include \"lvgl.h\"",
        "",
        f"#define AVATAR_SLOT_COUNT {N}",
        f"#define AVATAR_IMG_SIZE {SIZE}",
        "",
    ]
    descs = []
    for i in range(N):
        px = render_slot(i)
        name = f"avatar_{i + 1}_map"
        parts.append(c_array(name, px))
        stride = SIZE * 2
        parts.append(
            f"\nstatic const lv_image_dsc_t avatar_{i + 1} = {{\n"
            f"    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
            f"    .header.cf = LV_COLOR_FORMAT_RGB565,\n"
            f"    .header.w = {SIZE},\n"
            f"    .header.h = {SIZE},\n"
            f"    .header.stride = {stride},\n"
            f"    .data_size = {len(px) * 2},\n"
            f"    .data = {name},\n"
            f"}};\n"
        )
        descs.append(f"    &avatar_{i + 1}")

    parts.append("static const lv_image_dsc_t *const avatar_slots[AVATAR_SLOT_COUNT] = {")
    parts.append(",\n".join(descs))
    parts.append("};")
    parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({N} x {SIZE}x{SIZE} RGB565)")

    web_dir = ROOT / "demos" / "server" / "v1_product" / "web" / "avatars"
    web_dir.mkdir(parents=True, exist_ok=True)
    try:
        from PIL import Image
    except ImportError:
        print("PIL not installed — skip web PNG export")
        return
    for i in range(N):
        px = render_slot(i)
        im = Image.new("RGB", (SIZE, SIZE))
        for y in range(SIZE):
            for x in range(SIZE):
                v = px[y * SIZE + x]
                r = ((v >> 11) & 0x1F) << 3
                g = ((v >> 5) & 0x3F) << 2
                b = (v & 0x1F) << 3
                im.putpixel((x, y), (r, g, b))
        out_png = web_dir / f"avatar-{i + 1}.png"
        im.save(out_png)
    print(f"wrote {N} PNGs -> {web_dir}")


if __name__ == "__main__":
    main()
