"""a05 — Pack PNG + WAV into C arrays the firmware can flash.

Default dest is firmware/assets/persona.example (committed stand-ins).
Your likeness:  --dest firmware/assets/persona   (gitignored overlay)
"""

from __future__ import annotations

import argparse
import sys
import wave
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "demos" / "persona"))

from _shared import paths


def rgb565_bytes(im: Image.Image) -> bytes:
    im = im.convert("RGB")
    out = bytearray()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b = im.getpixel((x, y))
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out += v.to_bytes(2, "little")
    return bytes(out)


def c_bytes(name: str, data: bytes, cols: int = 12) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) == cols or i == len(data) - 1:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    return "\n".join(lines)


def write_idle_h(dest: Path, im: Image.Image) -> None:
    data = rgb565_bytes(im)
    w, h = im.size
    stride = w * 2
    body = c_bytes("persona_idle_map", data)
    text = f"""#pragma once
/* Generated by demos/persona/05_pack/pack.py — do not edit by hand. */
#include "lvgl.h"

{body}

static const lv_image_dsc_t persona_idle = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_RGB565,
    .header.w = {w},
    .header.h = {h},
    .header.stride = {stride},
    .data_size = {len(data)},
    .data = persona_idle_map,
}};
"""
    dest.write_text(text, encoding="utf-8")
    print(f"idle {w}x{h} RGB565 {len(data)} bytes -> {dest}")


def write_greeting_h(dest: Path, wav_path: Path) -> None:
    with wave.open(str(wav_path), "rb") as wav:
        if wav.getsampwidth() != 2 or wav.getnchannels() != 1:
            raise SystemExit("greeting wav must be s16le mono")
        rate = wav.getframerate()
        pcm = wav.readframes(wav.getnframes())
    body = c_bytes("persona_greeting_pcm", pcm)
    text = f"""#pragma once
/* Generated by demos/persona/05_pack/pack.py — do not edit by hand. */
#include <stdint.h>

#define PERSONA_GREETING_RATE {rate}
#define PERSONA_GREETING_BYTES {len(pcm)}

{body}
"""
    dest.write_text(text, encoding="utf-8")
    print(f"greeting {len(pcm)} bytes @{rate} Hz -> {dest}")


def main() -> int:
    parser = argparse.ArgumentParser(description="PNG/WAV → C headers for p10/p11.")
    parser.add_argument("--png", type=Path, default=paths.IDLE)
    parser.add_argument("--wav", type=Path, default=paths.GREETING)
    parser.add_argument(
        "--dest",
        type=Path,
        default=paths.EXAMPLE,
        help="persona.example (committed) or persona (your overlay, gitignored)",
    )
    parser.add_argument("--idea", help="Pack data/persona/ideas/<name>.png instead of idle")
    args = parser.parse_args()
    paths.ensure_data()

    png = args.png
    if args.idea:
        png = paths.IDEAS / f"{args.idea}.png"
    if not png.is_file():
        print(f"FAIL missing {png} (run a02 / a04 first)")
        return 1
    if not args.wav.is_file():
        print(f"FAIL missing {args.wav} (run a03 first)")
        return 1

    dest = args.dest
    dest.mkdir(parents=True, exist_ok=True)
    im = Image.open(png).convert("RGB")
    if im.size[0] > 240 or im.size[1] > 240:
        im.thumbnail((200, 200), Image.Resampling.LANCZOS)
    write_idle_h(dest / "persona_idle.h", im)
    write_greeting_h(dest / "persona_greeting.h", args.wav)
    print("-- PASS a05")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
